version: "3.9"
services:
  aggregator:
    build: .
    image: uts-aggregator:latest
    container_name: aggregator
    environment:
      - DEDUP_DB_PATH=/app/data/dedup.db
    volumes:
      - ./data:/app/data
    ports:
      - "8080:8080"
